config/routes.rb
TeacherGap::Application.routes.draw do

  resources :schools do
    collection do
      post 'search'
    end
  end

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :news_items
  resources :searches

  root :to => 'news_items#index'

  resources :news_items do
    get :test
  end

  resources :news_items do
    resources :comments
  end

  match 'signup' => 'users#create', :as => :signup
  match 'login' => 'sessions#create', :as => :login
  match 'about', :controller => "static"

end

app/views/layouts/_filter_source.html.erb
<div class="filter row-fluid">
  <div class='span6 offset2'>
    <div class='span1'><a href="#">Tumblr</a></div>
    <div class='span1'><a href="#">Twitter</a></div>
    <div class='span1'><a href="#">Reddit</a></div>
    <div class='span1'><a href="#">Instagram</a></div>
  </div>
</div>

app/views/layouts/_filter_type.html.erb
<div class="filter row-fluid">
  <div class='span6'>
    <div class='span1'><a href="#">Photos</a></div>
    <div class='span1'><a href="#">Quotes</a></div>
    <div class='span1'><a href="#">Statuses</a></div>
    <div class='span1'><a href="#">Answers</a></div>
    <div class='span1'><a href="#">Chats</a></div>
  </div>
</div>

app/views/layouts/_footer.html.erb
    <div class="footer">
      <div class="container narrow">
        <p class="muted credit">By <a href="https://github.com/charmcitygavin">Gavin</a>, <a href="https://github.com/kbasye/">Katey</a>, and <a href="https://github.com/jam-tmrw/">James</a>.</p>
      </div>
    </div>

app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class = 'container'>

      <ul class="nav span3">
      <% if current_user %>
        <h1><li><%= link_to 'SchoolSay', user_path(current_user) %>
           </li></h1>
           <span class='tag_line'>What schools are saying, in real time.</span>
      <% else %>
        <h1><li class ='active'><%= link_to 'SchoolSay', root_url %> </li></h1>
        <span class='tag_line'>What schools are saying</span>
      <% end %>
      </ul>

      <ul class='nav span4 search-bar'>
        <li class="dropdown">
          <a class="dropdown-toggle" href="#" data-toggle="dropdown">Find School by Location <strong class="caret"></strong></a>
            <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
              <%= render 'layouts/search' %>
            </div>
        </li>
      </ul>


      <ul class ='nav pull-right span4'>
        <li><%= render 'layouts/login_signup' %></li>
      </ul>

    </div>
  </div>
</div>

app/views/layouts/_loader.html.erb
<div id="loader">
  <h2><img src="/assets/ajax-loader.gif"> Loading Content...</h2>
</div>

app/views/layouts/_login_signup.html.erb
<% if current_user %>       
  <li><%= link_to "Log out", session_path(current_user), :method => :delete %></li>
<% else %>
  <li class="dropdown">
    <a class="dropdown-toggle" href="#" data-toggle="dropdown">Sign Up <strong class="caret"></strong></a>
      <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
        <%= render 'users/sign_up' , :user => @user %>
      </div>
  </li>
  <li class="divider-vertical"></li>
  
  <li class="dropdown">
    <a class="dropdown-toggle" href="#" data-toggle="dropdown">Log In <strong class="caret"></strong></a>
      <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
        <%= render 'sessions/login' , :user => @user %>
      </div>
  </li>
<% end %>

app/views/layouts/_search.html.erb
<div class=".navbar-search pull-left">
    <% @states = [ ["AL", "Alabama"], ["AK", "Alaska"], ["AZ", "Arizona"], ["AR", "Arkansas"], ["CA", "California"], ["CO", "Colorado"], ["CT", "Connecticut"], ["DE", "Delaware"], ["DC", "District of Columbia"],["FL", "Florida"], ["GA", "Georgia"], ["HI", "Hawaii"], ["ID", "Idaho"], ["IL", "Illinois"], ["IN", "Indiana"], ["IA", "Iowa"], ["KS", "Kansas"], ["KY", "Kentucky"], ["LA", "Louisiana"], ["ME", "Maine"], ["MD", "Maryland"], ["MA", "Massachusetts"], ["MI", "Michigan"], ["MN", "Minnesota"], ["MS", "Mississippi"], ["MO", "Missouri"], ["MT", "Montana"], ["NE", "Nebraska"], ["NV", "Nevada"], ["NH", "New Hampshire"], ["NJ", "New Jersey"], ["NM", "New Mexico"], ["NY", "New York"], ["NC", "North Carolina"], ["ND", "North Dakota"], ["OH", "Ohio"], ["OK", "Oklahoma"], ["OR", "Oregon"], ["PA", "Pennsylvania"], ["RI", "Rhode Island"], ["SC", "South Carolina"], ["SD", "South Dakota"], ["TN", "Tennessee"], ["TX", "Texas"], ["UT", "Utah"], ["VT", "Vermont"], ["VA", "Virginia"], ["WA", "Washington"], ["WV", "West Virginia"], ["WI", "Wisconsin"], ["WY", "Wyoming"] ] %>

    <%= form_tag(search_schools_path) do %>
      <%= text_field_tag(:zip, nil, :placeholder => "Enter Zip") %>
      <%= text_field_tag(:city, nil, :placeholder => "Enter City") %>
      <%= hidden_field_tag(:header, true) %>
      <%= select_tag :state, options_for_select(@states.map{ |s| [s.last, s.first] }) %>
      <%= submit_tag 'Submit', :class => 'btn' %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolSay</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>

    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js" %>

    <link href='http://fonts.googleapis.com/css?family=Arvo:400,700' rel='stylesheet' type='text/css'>

    <%= csrf_meta_tags %>
  </head>
  <body>
      <%= render 'layouts/header' %>
    <div class='container'>

      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>